# Site
repository: com3dian/com3dian.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Zehao Lu
title: M.Sc Artificial Intelligence, Utrecht University
email: com3dian@outlook.com
website: https://com3dian.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username: com3dian
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: zehao-lu-93923a146
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi I'm a graduate student major in AI. I possess robust mathematical and
  statistical skills, along with a comprehensive comprehension of both the
  theoretical and practical aspects of machine learning. I have hands-on
  experience working with popular ML/DL libraries, such as pytorch, tensorflow,
  keras, sklearn, Scipy. I am proficient in utilizing <mark>Apache Spark</mark>
  (pyspark) for big data processing. I'm also a open source lover.

  My interests includes Natural Language Processing(**NLP**)/Natural Language
  Generation(**NLG**), Large Language Model(**LLM**), Reinforcement Learning(**RL**),
  **AI4science** and AI for IT Operations(**AIops**).

  I am mostly sklled in <mark>Python</mark>. I am also skilled in:
  <mark>R</mark> programming language and <mark>C</mark>. I would like to try
  <mark>Julia</mark> as well.

  Actively learning <mark>C#</mark> for Unity.

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Utrecht University
        caption: 2021 - 2023
        sub_title: MSc Artificial Intelligence
        quote: >
          Founded in 1636, Utrecht University is internationally recognized for
          its high-quality education and research, and it consistently ranks
          among the top universities in Europe.
        description: | # this will include new lines to allow paragraphs
          **Courses**: Machine Learning for Human Vision and Language,
          Advanced Machine Learning, Methods in AI Research, Computer Vision,
          Natural Language Processing, Data Intensive System,
          Computational Argumentation, Evolutionary Computing



      - layout: left
        title: Peking University
        caption: 2010 - 2013
        sub_title: BSc Mathematics
        quote: >
          Best Univeristy in China.
        description: | # this will include new lines to allow paragraphs
          **Courses**: Introduction to Computation, Data Structure and Algorithm,
          Mathematical Analysis, Linear Algebra, Mathematical Statistics,
          Probability Theory, Applied Regression Theory, Machine Learning,
          Statistical Learning, Deep learning, Introduction to Numerical Analysis,
          Graph Theory

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ML6
        link: https://www.ml6.eu/
        # link_text: boringcompany.com
        sub_title: Machine Learning Intern · Internship
        caption: Jan 2023 - Present
        quote: >
          Assisting companies in leveraging AI to generate business outcomes by
          offering AI-related services. I worked with NLP
          chapter(https://www.ml6.eu/chapters/nlp-chapter).
        description: | # this will include new lines to allow paragraphs
          The objective of this graduate internship project is to implement an
          AI model capable of:

            - Analyze a research paper in (editable) .pdf form and extract
            meaningful content as much as possible;

            - Abstarctively summarizes the extracted contents(mainly text, but
            could also include tables, pictures, and formulas) and construct the knowledge graph;

            - Generate a slide explaining the paper accordingly. The slide can
            be used in a presentation or to help understand the original paper;

          **Other words**: fine tune a large language model for long text summarization
          using Google cloud platform(<mark>GCP</mark>).


      - layout: left
        title: ML6
        link: https://www.ml6.eu/
        # link_text: boringcompany.com
        sub_title: Machine Learning Intern · Internship
        caption: Sep 2022 - Dec 2022 · 4 mos
        quote: >
          Assisting companies in leveraging AI to generate business outcomes by
          offering AI-related services. I worked with [structure data
          team](https://www.ml6.eu/chapters/structured-data).
        description: | # this will include new lines to allow paragraphs
          Research similarity metrics(Wasserstein distance) and contribute to
          python open-source libraries.

            - Implement the Wasserstein distance metric between distributions in
            python.

            - Contribute to open-source communities such as <mark>Scipy</mark>.

            - Apply the Wasserstein metric on the client's data for anomaly
            detection.

          **Other words**: suggest a [multi dimensional wasserstein_distance
          function](https://github.com/scipy/scipy/issues/17290) in Scipy and
          start a PR.

      - layout: left
        title: 4Paradigm
        link: https://en.4paradigm.com/
        # link_text: boringcompany.com
        sub_title: Machine Learning Engineer(one year contract) · Full-time
        caption: Aug 2020 - Aug 2021 · 1 yr 1 mo
        quote: >
          Developing Data center and modern machine learning database. I worked
          in the AI team of the time serial data center development department.
        description: | # this will include new lines to allow paragraphs
          Developing AI algorithms for IT Operations
            - Developed an algorithm, Kmeans over time serial data, for
            converting time series to sequences;
            - Combined the 'Kmeans over time series' algorithm with the CAD_OSE
            algorithm for contextual anomaly detection;
            - Applied DeepAR and Prophet algorithm on time series forecasting;
            - Applied Isolation Tree algorithm on anomaly detection task.

          **Other words**: design, test and apply algorithms on time serial data.

      - layout: left
        title: BMW China
        link: https://www.bmw.com.cn/
        # link_text: boringcompany.com
        sub_title: Machine Learning Intern · Internship
        caption: Sep 2019 - Dec 2019 · 4 mos
        quote: >
          Developing Data center and modern machine learning database. I worked
          in the AI team of the time serial data center development department.
        description: | # this will include new lines to allow paragraphs
          Improving machine learning system for risk assessment
            - Data discovery and building predictive, prescriptive models
            utilizing machine learning algorithms supported by strong
            statistical theory;
            - Risk analysis of financial loans given to customers.

          **Other words**: design, test and apply algorithms on time serial data.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.



  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Football
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
